version: "3.6"

services:
  aeternity:
    image: aeternity/aeternity:v5.4.1
    volumes:
      - ./aeternity.yaml:/home/aeternity/.aeternity/aeternity/aeternity.yaml
    ports:
      - "3013:3013"
      - "3113:3113"

  compiler:
    image: aeternity/aesophia_http:v4.2.0
    ports:
      - "3080:3080"
